---
- name: Deploy code
  command:
    chdir=/opt/{{ project_name }}/{{ repo_path }}
    slc deploy --service {{ item.key }}

- name: Set proper environment variable
  command:
    slc ctl env-set {{ item.key }} \
    {% for key, value in item.value.iteritems() %}{{ key }}="{{ value }}" {% endfor %}
