---
# tasks file for deploying strongloop code
- name: Set destination for the code
  set_fact:
    repo_path: "{{ repo_url | basename | regex_replace('.git','') }}"

#
# Add the support for multi versions of the same code
#
- include: strongloop_deploy.yml
  with_items:
      "{{ strongloop_instances | default([]) }}"
